version: "3"
services:
  signaling:
    image: signaling-server:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - 3000:3000
      - 3306:3306
      - 5228:5228
      - 5229:5229
      - 5230:5230
      - 6379:6379
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - FIREBASE_ACCOUNT_TYPE=${FIREBASE_ACCOUNT_TYPE}
      - FIREBASE_ACCOUNT_PROJECT_ID=${FIREBASE_ACCOUNT_PROJECT_ID}
      - FIREBASE_ACCOUNT_PRIVATE_KEY_ID=${FIREBASE_ACCOUNT_PRIVATE_KEY_ID}
      - FIREBASE_ACCOUNT_PRIVATE_KEY=${FIREBASE_ACCOUNT_PRIVATE_KEY}
      - FIREBASE_ACCOUNT_CLIENT_EMAIL=${FIREBASE_ACCOUNT_CLIENT_EMAIL}
      - FIREBASE_ACCOUNT_CLIENT_ID=${FIREBASE_ACCOUNT_CLIENT_ID}
      - FIREBASE_ACCOUNT_AUTH_URI=${FIREBASE_ACCOUNT_AUTH_URI}
      - FIREBASE_ACCOUNT_TOKEN_URI=${FIREBASE_ACCOUNT_TOKEN_URI}
      - FIREBASE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL}
      - FIREBASE_ACCOUNT_CLIENT_X509_CERT_URL=${FIREBASE_ACCOUNT_CLIENT_X509_CERT_URL}
      - SEQUELIZE_SCHEMA=${SEQUELIZE_SCHEMA}
      - SEQUELIZE_USER_NAME=${SEQUELIZE_USER_NAME}
      - SEQUELIZE_PASSWORD=${SEQUELIZE_PASSWORD}
      - SEQUELIZE_OPTION_HOST=${SEQUELIZE_OPTION_HOST}
      - SEQUELIZE_OPTION_DIALECT=${SEQUELIZE_OPTION_DIALECT}
    volumes:
      - ./:/usr/local/src
